services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - postgres
  #     - mongo

  postgres:
    image: postgres:latest
    container_name: postgres-csv
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo-csv
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo_data:/data/db

# Uncomment to persist data on local drive
# volumes:
#   postgres_data:
#   mongo_data:
